### ISSUE TITLE
Nakshatras calculation not matiching with drikpanchang.com

### ISSUE THREAD

**Issue by gitbitlit** [kadvar/MRLAstro#20]
||Pranams to Guru Parampara||

Panchanga tab shows Daily Panchanga of Visakhapatnam, India, Nakshatra shown here not matching with drikPanchang.com.

For example, Date time now : Jul 30 11:13 AM Location : Visakhapatnam, India

**Nakshatra(s) calculated by MRLAstro is** 

- Nakshatra: Rohiṇī ends 19:03 *** Nakshatras begin from Krittika
- Nakshatra: Bharaṇī ends 19:03 *** Nakshatras begin from Aśvinī - Traditional

**Nakshatra calculated by drikPanchang.com is**

- Nakshatra: Revathi ends 14:03 

Am very much new to Astrology, please forgive me if my above understandings are completely wrong.

**Comment by kadvar** [comment]
Namaste, The difference you see happens because this website use the Sayana (Tropical) zodiac for calculating planetary positions while traditional panchangas (like drikpanchang) use the Nirayana (Sidereal) zodiac. 

Our Guru taught us that the Sayana system was scientific and that it was the one used by our ancient Rishis. The Nirayana zodiac was a later interpolation. You can read a well written article on the differences here http://www.vicdicara.com/tropical_vedic_astrology.php

There is a approx. 23 degree difference in planetary positions between these two systems so the position of the Moon which is used to calculate the nakshatra will be different for a given day. You can see the tropical zodiac positions here https://www.astro.com/swisseph/ae/2000/ae_2021.pdf 

Note that the tithe does not change irrespective of which system you use as it is the angle between the Sun and the Moon which remains constant between the two zodiacs.

Hope this helps.

**Comment by gitbitlit** [comment]
||Pranams to Guru Parampara||

Namaste, being a beginner it certainly helps me.
Thank you for taking time to correct my understanding.
